### PR TITLE
feat: allow anonymous and pseudonymous (guest) log ins.

### PR DESCRIPTION
**Pull request by emembrives**
Change the admin interface and server to allow guest log-ins (users with
a username but no password).

Change the group login page to allow anonymous and pseudonymous login,
with a dedicated and more explicit button.

Refs: #63

# Purpose

Fixes Issue #63: allows anonymous access

Add the galene feature of allowing "guest" access to groups : similar to anonymous, but with a user-chosen username.

## Approach

[Galene README file](https://galene.org/README.html), section "Password authorization", explains that the user entry `{}` (empty JSON object) means any user with a username and no password (named "guest" here). Instead of modifying the Pyrite user system to add such user, and modify every endpoint to allow for a user object without a name, I added a boolean entry in the Pyrite group object named `public-access`, and added conversion to/from this boolean to the Galene empty user `{}`.

On the group login page, I modified the logic to allow for anonymous or guest access by allowing, when appropriate, login with no username and/or no password. I also added a dedicated button to make the UI more explicit.

I ran the linter (`npm run lint`), but have not found how to run any automated test. I added French and Dutch translations, but I only speak French.

## Open Questions and Pre-Merge TODOs

- [ ] Run automated tests, if any
- [ ] Check Dutch (NL) translations

### CODE REVIEW

**Comment by jvanveen** [comment]
Hey, thanks for your contribution! Looks good. I'll give it a try this week.

**Review by jvanveen — CHANGES_REQUESTED** [review]

**Comment by jvanveen** [comment]
I suppose the login flow could look something like this:
Screenshot_20220819_102025

**Comment by emembrives** [comment]
Thanks for the review. I'll work on the changes.

**Comment by jvanveen** [comment]
I pushed some proposed UI changes to feat/105-anonymous-guest-login and added you to the repo contributors. Continue on that branch? I'll create a new PR from it.

**Pull request closed without merging**
