### PR TITLE
Feat/108 anonymous guest login

### PR DESCRIPTION
**Pull request by jvanveen**
Change the admin interface and server to allow guest log-ins (users with
a username but no password).

Change the group login page to allow anonymous and pseudonymous login,
with a dedicated and more explicit button.

Refs: #63

# Purpose

Fixes Issue #63: allows anonymous access

Add the galene feature of allowing "guest" access to groups : similar to anonymous, but with a user-chosen username.

## Approach

[Galene README file](https://galene.org/README.html), section "Password authorization", explains that the user entry `{}` (empty JSON object) means any user with a username and no password (named "guest" here). Instead of modifying the Pyrite user system to add such user, and modify every endpoint to allow for a user object without a name, I added a boolean entry in the Pyrite group object named `public-access`, and added conversion to/from this boolean to the Galene empty user `{}`.

On the group login page, I modified the logic to allow for anonymous or guest access by allowing, when appropriate, login with no username and/or no password. I also added a dedicated button to make the UI more explicit.

I ran the linter (`npm run lint`), but have not found how to run any automated test. I added French and Dutch translations, but I only speak French.

## Open Questions and Pre-Merge TODOs

- [x] Run automated tests, if any
- [x] Check Dutch (NL) translations

### CODE REVIEW

**Comment by jvanveen** [comment]
The UI now shows either a switch (user/guest) or a radio (user/guest/anonymous). I'm not sure whether these types of login can be cleanly compartmentalized; e.g. a user login with a non-existing username/password would result in a guest login. Although, I think it's more clear than implicitly using the username/password fields for the type of login. 

I noticed that the locking info for the group seems to be broken. When the group is locked, there shouldn't be a guest/anonymous option listed.

**Comment by jvanveen** [comment]
Last commit fixes the locked status and hides the login options when the group is locked. Do you think the anonymous/guest login feature is good to go as it is now?

**Comment by emembrives** [comment]
Thanks, this looks very good.

The only "change" I would do is to put the lowest level of authorization as the default value on the group login page;
I coded this in [my repo](https://github.com/emembrives/pyrite/tree/feat/105-anonymous-guest-login): users with an account (username + password) can presumably receive more training on the use of the site (ie. can be told/trained to click an extra button) whereas guest or anonymous users are more likely much less trained and invested, so we should make it as easy as possible for them.

It isn't a big deal for me either way, so feel free to merge without my change (I didn't put my change directly on this branch so it is easier for you to reject if you prefer).

**Comment by jvanveen** [comment]
Sounds look a good idea to change the default order. Besides in the mounted hook, it should also be added in the watcher (triggered when changing groups). No need for a merge request. If you like, you can this commit directly. I'll merge this one alreay.

**Pull request merged**
